import 'package:utilitypoint/env/env.dart';

class AppUrls{
  static const baseUrl =Env.baseUrlStaging;
  static const register= "${baseUrl}auth/register";
  static const emailVerification="${baseUrl}user/verify_email";
  static const resendEmailVerification="${baseUrl}user/resend_email_verification_code";
  static const setPin="${baseUrl}user/set_user_pin";
  static const changePin="${baseUrl}user/change_user_pin";
  static const setUserInfo="${baseUrl}user/update_user";
  static const login="${baseUrl}auth/login";
  static const forgotPassword="${baseUrl}auth/forgot_password";
  static const createNewPassword="${baseUrl}auth/complete_password_reset";
  static const completeTwoFactorAuthentication="${baseUrl}auth/complete_two_factor_authentication";
  static const resendCompleteTwoFactorAuthentication="${baseUrl}auth/resend_2fa_code";
  static const getUserCards="${baseUrl}user/view_virtual_cards";
  static const getCardTransaction="${baseUrl}user/virtual_card_transactions";
  static const createUserCard="${baseUrl}user/create_virtual_card";
  static const createVirtualAcct="${baseUrl}user/generate_naira_virtual_accounts";
  static const topUpCard="${baseUrl}user/topup_virtual_card";
  static const freezeUserCard="${baseUrl}user/freeze_card";
  static const unFreezeUserCard="${baseUrl}user/unfreeze_card";
  static const getTransactionHistory="${baseUrl}user/fetch_transactions";
  static const getUserSettings="${baseUrl}settings";
  static const getUserVirtualAccounts="${baseUrl}user/fetch_naira_virtual_accounts";
  static const getUserDetails="${baseUrl}user/fetch_single_user";
  static const getExchangeRate="${baseUrl}fetch_currency_conversion_setting";
  static const getNairaFunding="${baseUrl}fetch_naira_funding_options";
  static const getNetworks="${baseUrl}user/fetch_networks";
  static const getProduct="${baseUrl}user/fetch_products";
  static const getProductDataPlanCategory="${baseUrl}user/fetch_product_plan_categories";
  static const getProductPlans="${baseUrl}user/fetch_product_plans";
  static const buyElectricity="${baseUrl}user/buy_electricity";
  static const confirmSmartCableName="${baseUrl}user/validate_cable_tv";
  static const confirmElectricityMeterName="${baseUrl}user/validate_metre_number";
  static const cableSubscription="${baseUrl}user/buy_cable_tv";
  static const buyAirtime="${baseUrl}user/buy_airtime";
  static const buyDollar="${baseUrl}currency/buy_dollar";
  static const buyData="${baseUrl}user/buy_data";
  static const buyCableSub="${baseUrl}user/buy_cable_tv";
  static const updateUserPassword="${baseUrl}user/reset_password";
  static const resetUserPin="${baseUrl}user/change_user_pin";
  static const updateUserDetails="${baseUrl}user/update_user";
  static const logOut="${baseUrl}auth/logout";
  static const getUserNotification="${baseUrl}user/fetch_user_notifications";
  static const markNotification="${baseUrl}user/toggle_user_notification_read_status";
  static const getNairaTransactions="${baseUrl}user/fetch_naira_wallet_transactions";
  static const getDollarsTransactions="${baseUrl}user/fetch_dollar_wallet_transactions";
  static const getUserUploadedKYC="${baseUrl}kyc/fetch_user_kyc_details";
  static const getUSerKYCVerificationStatus="${baseUrl}kyc/user_verification_status";
  static const uploadKYCDocumentC="${baseUrl}kyc/upload_user_kyc_document";
  static const uploadBVNDocumentC="${baseUrl}kyc/user_bvn_verification";
  static const updateAppSetting="${baseUrl}user/update_appside_setting";
  static const getFAQ="${baseUrl}faqs";
  static const getSingleVirtualCard="${baseUrl}user/view_single_virtual_card";
  static const setUserIdentifier="${baseUrl}user/update_user_unique";
  static const getSingleUserDetails="${baseUrl}user/fetch_single_user";
  static const getUserWalletBalance="${baseUrl}user/fetch_wallet_balance";

  static const validateBvnOtp= "${baseUrl}kyc/verify_bvn_phone_otp";
 // static const completeTwoFactorAuthentication=
 // "${baseUrl}auth/complete_two_factor_authentication";
}