import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

///Height
var height4=SizedBox(height: 4.h,);
var height6=SizedBox(height: 6.h,);
var height8=SizedBox(height: 8.h,);
var height10=SizedBox(height: 10.h,);
var height12=SizedBox(height: 12.h,);
var height16=SizedBox(height: 16.h,);
var height20=SizedBox(height: 20.h,);
var height22=SizedBox(height: 22.h,);
var height24=SizedBox(height: 24.h,);
var height26=SizedBox(height: 26.h,);
var height28=SizedBox(height: 28.h,);
var height30=SizedBox(height: 30.h,);
var height35=SizedBox(height: 35.h,);
var height40=SizedBox(height: 40.h,);
var height45=SizedBox(height: 45.h,);
var height50=SizedBox(height: 50.h,);
var height55=SizedBox(height: 55.h,);
var height60=SizedBox(height: 60.h,);
var height61=SizedBox(height: 61.h,);
var height62=SizedBox(height: 62.h,);
var height63=SizedBox(height: 63.h,);
var height67=SizedBox(height: 67.h,);
var height70=SizedBox(height: 70.h,);
var height85=SizedBox(height: 85.h,);
var height90=SizedBox(height: 90.h,);
var height120=SizedBox(height: 120.h,);